meta_title: "SOS Food - Envoyez un SMS - Trouvez un repas solidaire"
meta_description: "Trouver un repas solidaire. Simple comme un SMS. SOS Food est un service de SMS par géolocalisation en France."
meta_image: "soup_kitchen_card_overlay.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@SOSFoodorg" # indispensable pour les Twitter Cards
